# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venavisos.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import var

class Ui_dlgAvisos(object):
    def setupUi(self, dlgAvisos):
        dlgAvisos.setObjectName("dlgAvisos")
        dlgAvisos.setWindowModality(QtCore.Qt.WindowModal)
        dlgAvisos.resize(400, 209)
        self.lblAvisos = QtWidgets.QLabel(dlgAvisos)
        self.lblAvisos.setGeometry(QtCore.QRect(170, 20, 61, 61))
        self.lblAvisos.setText("")
        self.lblAvisos.setPixmap(QtGui.QPixmap(":/newPrefix/aviso.png"))
        self.lblAvisos.setScaledContents(True)
        self.lblAvisos.setObjectName("lblAvisos")
        self.btnAceptaviso = QtWidgets.QPushButton(dlgAvisos)
        self.btnAceptaviso.setGeometry(QtCore.QRect(110, 160, 75, 23))
        self.btnAceptaviso.setObjectName("btnAceptaviso")
        self.btnboxAceptCancel = QtWidgets.QButtonGroup(dlgAvisos)
        self.btnboxAceptCancel.setObjectName("btnboxAceptCancel")
        self.btnboxAceptCancel.addButton(self.btnAceptaviso)
        self.btnCancelaviso = QtWidgets.QPushButton(dlgAvisos)
        self.btnCancelaviso.setGeometry(QtCore.QRect(210, 160, 75, 23))
        self.btnCancelaviso.setObjectName("btnCancelaviso")
        self.btnboxAceptCancel.addButton(self.btnCancelaviso)
        var.lblMensaviso = QtWidgets.QLabel(dlgAvisos)
        var.lblMensaviso.setGeometry(QtCore.QRect(90, 100, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        var.lblMensaviso.setFont(font)
        var.lblMensaviso.setAlignment(QtCore.Qt.AlignCenter)
        var.lblMensaviso.setObjectName("lblMensaviso")
        self.retranslateUi(dlgAvisos)
        QtCore.QMetaObject.connectSlotsByName(dlgAvisos)

    def retranslateUi(self, dlgAvisos):
        _translate = QtCore.QCoreApplication.translate
        dlgAvisos.setWindowTitle(_translate("dlgAvisos", "Aviso"))
        self.btnAceptaviso.setText(_translate("dlgAvisos", "Aceptar"))
        self.btnCancelaviso.setText(_translate("dlgAvisos", "Cancelar"))
        var.lblMensaviso.setText(_translate("dlgAvisos", "¿Esta seguro que desea eliminar?"))
import avisos_rc
