# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vensalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.setWindowModality(QtCore.Qt.WindowModal)
        dlgSalir.resize(364, 156)
        dlgSalir.setModal(True)
        self.lblMensalir = QtWidgets.QLabel(dlgSalir)
        self.lblMensalir.setGeometry(QtCore.QRect(40, 70, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMensalir.setFont(font)
        self.lblMensalir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lblMensalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMensalir.setObjectName("lblMensalir")
        self.label = QtWidgets.QLabel(dlgSalir)
        self.label.setGeometry(QtCore.QRect(160, 10, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/iconoaviso.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btnAceptar = QtWidgets.QPushButton(dlgSalir)
        self.btnAceptar.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnBoxSalir = QtWidgets.QButtonGroup(dlgSalir)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.btnBoxSalir.addButton(self.btnAceptar)
        self.btnCancelar = QtWidgets.QPushButton(dlgSalir)
        self.btnCancelar.setGeometry(QtCore.QRect(200, 110, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")
        self.btnBoxSalir.addButton(self.btnCancelar)

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Aviso"))
        self.lblMensalir.setText(_translate("dlgSalir", "¿Está seguro que desea salir de la aplicación?"))
        self.btnAceptar.setText(_translate("dlgSalir", "Aceptar"))
        self.btnCancelar.setText(_translate("dlgSalir", "Cancelar"))
import avisosalir_rc
